databases:
  - name: taskflow-db
    databaseName: taskflow_db
    user: taskflow_user

services:
  - type: web
    name: taskflow-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn taskflow_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
