[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --no-input']

[start]
cmd = 'python manage.py migrate && gunicorn taskflow_backend.wsgi:application --bind 0.0.0.0:$PORT'
